### ISSUE TITLE
filter_bam_file issue

### ISSUE THREAD

**Issue by changostraw** [aertslab/popscle_helper_tools#10]
Hello, Thanks for the tools!
when I use the filtered bam file for the demuxlet pileup, I get 0 reads (see output below). The vcf file I use has only been subsetted to the samples in the pool and I haven't removed any rows. Here is the code I used:

`/popscle_helper_tools-master/filter_bam_file_for_popscle_dsc_pileup.sh \
   /DIS_Cohort/INS_PoolD_count/outs/possorted_genome_bam.bam \
  /DIS_Cohort/INS_PoolD_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz \
  /Genotype/donorGT/imputed/DIS_INS_PoolD.vcf \
  /DIS_Cohort/INS_PoolD_count/outs/INS_PoolD_Dmux_popscle_dsc_pileup.bam`

and then used the bam file in the popscle which I run in singularity:

`singularity exec --bind /DIS_Cohort/INS_PoolD_count/outs --bind /Genotype/donorGT/imputed /project/rrg-gturecki/Sarah/Demuxafy.sif popscle dsc-pileup --sam /DIS_Cohort/INS_PoolD_count/outs/INS_PoolD_Dmux_popscle_dsc_pileup.bam --vcf /Genotype/donorGT/imputed/DIS_INS_PoolD.vcf --group-list /DIS_Cohort/INS_PoolD_count/outs/filtered_feature_bc_matrix/barcodes.tsv.gz --out /DIS_Cohort/Demuxafy/Demuxlet/imputed/INS_PoolD/pileup`

NOTICE [2023/03/01 11:53:22] - Finished loading 30965 droplet/cell barcodes to consider
NOTICE [2023/03/01 11:53:22] - Initializing BCF reader..
NOTICE [2023/03/01 11:53:22] - Finished identifying 4 samples to load from VCF/BCF
NOTICE [2023/03/01 11:53:22] - Initializing SAM reader..
NOTICE [2023/03/01 11:53:22] - Identified 25 overlapping chromosomes between VCF and BAM
NOTICE [2023/03/01 11:53:22] - WARNING: Cannot find AF field from INFO field in VCF file, now calculate AF from AC/AN
NOTICE [2023/03/01 11:53:22] - Reading 0 reads at chr1:1 and skipping 0
NOTICE [2023/03/01 11:53:22] - Finished reading 1 markers from the VCF file
NOTICE [2023/03/01 11:53:22] - Total number input reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of unmapped or QC-failed reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of read-QC-passed reads : 0 
NOTICE [2023/03/01 11:53:22] - Total number of skipped reads with ignored barcodes : 0
NOTICE [2023/03/01 11:53:22] - Total number of non-skipped reads with considered barcodes : 0
NOTICE [2023/03/01 11:53:22] - Total number of gapped/noninformative reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of base-QC-failed reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of redundant reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of pass-filtered reads : 0
NOTICE [2023/03/01 11:53:22] - Total number of pass-filtered reads overlapping with multiple SNPs : 0
NOTICE [2023/03/01 11:53:22] - Starting to prune out cells with too few reads...
NOTICE [2023/03/01 11:53:22] - Finishing pruning out 0 cells with too few reads...
NOTICE [2023/03/01 11:53:22] - Writing cell information
NOTICE [2023/03/01 11:53:22] - Finished writing cell information
NOTICE [2023/03/01 11:53:23] - Build indices for sparse matrix
NOTICE [2023/03/01 11:53:23] - Finished builing indices for sparse matrix

When I run demuxlet with the unfiltered bam file, there are so many reads it takes days to run, so I was really hoping to use this to cut down on run-time. I have also tried to filter the vcf more, but that creates an error: Cannot read any single variant from the vcf Thanks!

**Comment by ghuls** [comment]
Are you sure your VCF file has the same chromosome names as your BAM file?

**Comment by changostraw** [comment]
Yes, both vcf and bam are in the "chr1" format and in lexicographic order. Demuxlet won't run if this is not the case. In my case Demuxlet will run fine, it just takes a long time as my bam files are too big. I tried your tools to filter the bam but it only worked for freemuxlet. However, someone wrote me a script to filter my bams with my genotype vcfs and it works now. thanks
