### ISSUE TITLE
Lack of ">"?

### ISSUE THREAD

**Issue by XiaofeiSunUCSF** [aertslab/popscle_helper_tools#3]
Hi,
Thank you for this useful tool
One question regarding the last line in example
`./filter_bam_file_for_popscle_dsc_pileup.sh \
    ./samples_to_demultiplex/outs/possorted_genome_bam.bam \
    ./samples_to_demultiplex/outs/filtered_feature_bc_matrix/barcodes.tsv \
    samples.vcf \
    /tmp/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam`

Shall we add ">" in the last line as:
`./filter_bam_file_for_popscle_dsc_pileup.sh \
    ./samples_to_demultiplex/outs/possorted_genome_bam.bam \
    ./samples_to_demultiplex/outs/filtered_feature_bc_matrix/barcodes.tsv \
    samples.vcf \
    >/tmp/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam`

**Comment by ghuls** [comment]
The script requires 4 arguments, so no `>` should be used.
```bash
./filter_bam_file_for_popscle_dsc_pileup.sh \
   ./samples_to_demultiplex/outs/possorted_genome_bam.bam \
   ./samples_to_demultiplex/outs/filtered_feature_bc_matrix/barcodes.tsv \
   samples.vcf \
   /tmp/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam
```

**Comment by XiaofeiSunUCSF** [comment]
> The script requires 4 arguments, so no `>` should be used.
> 
> ```shell
> ./filter_bam_file_for_popscle_dsc_pileup.sh \
>    ./samples_to_demultiplex/outs/possorted_genome_bam.bam \
>    ./samples_to_demultiplex/outs/filtered_feature_bc_matrix/barcodes.tsv \
>    samples.vcf \
>    /tmp/samples_to_demultiplex.filter_bam_file_for_popscle_dsc_pileup.bam
> ```

Hi,

Thank you for your quick reply.
For some reason, I could not run your script successfully. 
I run my script as:
`#!/bin/env bash
#$ -cwd
#$ -j yes
#$ -m beas
#$ -pe smp 4
#$ -l mem_free=8G
#$ -l scratch=500G
#$ -l h_rt=2:00:00
module load Sali cmake
module load CBI htslib
module load CBI vcftools
module load CBI bcftools
module load CBI samtools/1.10
samtools --version
/wynton/home/malab/xiaofeisun/filter_bam_file_for_popscle_dsc_pileup.sh \
/wynton/scratch/malab/CITE5/CITE/outs/possorted_genome_bam.bam \
/wynton/scratch/malab/CITE5/CITE/outs/filtered_feature_bc_matrix/barcodes.tsv \
/wynton/home/malab/xiaofeisun/chr/rename.vcf \
/wynton/home/malab/xiaofeisun/tmp/cite5.bam
qstat -j $JOB_ID`

I tried to submit the jobs, but always stopped in a second.
Then I tried to run 'nohup sh my.sh & on HPC' to test. I got error here

> Error: "samtools" could not be found in PATH.
Error: The version of "samtools" (samtools is /wynton/home/cbi/shared/software/CBI/samtools-1.10/bin/samtools) should be 1.10 or $Error: The version of "samtools" (samtools is /wynton/home/cbi/shared/software/CBI/samtools-1.10/bin/samtools) should be 1.10 or $Usage:   filter_bam_file_for_popscle_dsc_pileup input_bam_filename barcodes_tsv_filename vcf_filename output_bam_filename

Purpose: Filter BAM file for usage with popscle dsc-pileup by keeping reads:
           - which overlap with SNPs in the VCF file
           - and which have a cell barcode contained in the cell barcode list
         Keeping only relevant reads for popscle dsc-pileup can speedup it up several hunderd times.
Error: The version of "samtools" (samtools is /wynton/home/cbi/shared/software/CBI/samtools-1.10/bin/samtools) should be 1.10 or $samtools 1.10                                                                                                                     Using htslib 1.10                                                                                                                 Copyright (C) 2019 Genome Research Ltd.                                                                                           /wynton/home/malab/xiaofeisun/filter_bam_file_for_popscle_dsc_pileup.sh: line 46: syntax error near unexpected token `}'          /wynton/home/malab/xiaofeisun/filter_bam_file_for_popscle_dsc_pileup.sh: line 46: `}'                                             scheduling info:            (Collecting of scheduler job information is turned off)                                                                                                                                                                                 samtools 1.10                                                                                                                     Using htslib 1.10                                                                                                                 Copyright (C) 2019 Genome Research Ltd.                                                                                           samtools 1.10                                                                                                                     Using htslib 1.10                                                                                                                 Copyright (C) 2019 Genome Research Ltd.                                                                                           samtools 1.10     



I load our HPC package to the script, but seems the script could not recognize the loaded package? Do you have any ideas?

Thanks
Xiaofei

**Comment by XiaofeiSunUCSF** [comment]
Thank you!
It works!
