### ISSUE TITLE
Use a barcode other than CB to do the prefiltering

### ISSUE THREAD

**Issue by cflerin** [aertslab/popscle_helper_tools#6]
Hi @ghuls ,

It seems that the `CB` barcode tag is always used to select barcodes from the bam file:
https://github.com/aertslab/popscle_helper_tools/blob/63e6481db4b156a7ade0003f8897b29c4a79790b/filter_bam_file_for_popscle_dsc_pileup.sh#L112
would it possible to include the option to select a different tag?

**Comment by ghuls** [comment]
Added in:
https://github.com/aertslab/popscle_helper_tools/commit/b2d773af361e2d9293fb231c20a771180f5d4b6a

**Comment by cflerin** [comment]
Thanks for the quick fix!
