### ISSUE TITLE
Building vcf file

### ISSUE THREAD

**Issue by Lopiniatre** [aertslab/popscle_helper_tools#7]
Thank you for building those helper tools to run demuxlet efficiently.
Do you have advice or reference for the best pipeline to generate the input.vcf file and especially how to merge vcf files from different genotypes. I'm pretty new to vcf generation and it's something that is never answered fully in the popscle github. I'm planning to use some RNAseq results from the different genotypes to generate their SNPs vcf files. But a clear description of the step-by-step pipeline to generate and correctly merged those vcf files would help.

Should I filter for 1000g common variants before proceeding with your pipeline:
only_keep_snps input.vcf \
  | calculate_AF_AC_AN_values_based_on_genotype_info \
  | filter_out_mutations_missing_genotype_for_one_or_more_samples \
  | filter_out_mutations_homozygous_reference_in_all_samples \
  | filter_out_mutations_homozygous_in_all_samples \
  > output.vcf
and proceed to pre-filter the bam to run popscle.

Thanks!

**Comment by ghuls** [comment]
If you have bulk RNAseq for all your genotypes, you could use the 1000g common variants VCF file and call all those positions on all BAM files and then filter the results.

**Comment by Lopiniatre** [comment]
Thank you for the suggestion, 
Which tool/function would you recommend to merge the vcf correctly to have all genotype info in 1 file?
